types for dta library were added
syngenta-digital/dta-node pull request #116
Opened 2022-04-19 08:33 UTC by MakarSantalov

2022-04-19 15:20 UTC, paulcruse-syn requested changes

2022-04-19 15:20 UTC, paulcruse-syn commented on types/index.d.ts
> +export type DtaEngines = 'dynamodb' | 'neo4j';
This needs to be broken out into different files to make this more extensible; basically 1 file per adapter type.

This file is too large.

2022-04-20 12:03 UTC, syngenta-aleksei-zolotykh commented
@MakarSantalov it looks like we need to add type property to package.json files

See documentation [here](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package)

2022-04-25 14:31 UTC, paulcruse-syn requested changes

2022-04-25 14:31 UTC, paulcruse-syn commented on typings/common.d.ts
> +export declare type BaseAdapterParams<TEngine extends string>  = {
Common, similar to utils, is considered an anti-pattern. 

Please break these up into separate files

2022-04-25 14:31 UTC, paulcruse-syn commented on typings/neo4j.d.ts
> +import {
This is too much in 1 file, please break these up into separate files.

2022-04-25 14:31 UTC, paulcruse-syn commented on typings/dynamodb.d.ts
> +declare type DynamoDBQueryOperation = 'query';
This is too much in 1 file, please break these up into separate files.

2022-04-27 16:14 UTC, paulcruse-syn approved these changes

2022-04-27 16:41 UTC, merged